name: Firebase Distribution

on:
  push:
    branches:
      - master

jobs:
  distribute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.44.0"

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          working-directory: android
          
          

      - name: Install Bundler
        run: gem install bundler

      - name: Install Gems
        run: bundle install

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Create Firebase Service Account
        run: |
          echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT }}' > google-service-account.json

      - name: Set Google Credentials
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/google-service-account.json" >> $GITHUB_ENV

      - name: Run Fastlane
        run: bundle exec fastlane distribute
        working-directory: android